name: preptime
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^7.0.1
  intl: any
  provider: ^6.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  # fonts:
  #   - family: NotoSerifBengali
  #     fonts:
  #       - asset: fonts/NotoSerifBengali-Regular.ttf
  #       - asset: fonts/NotoSerifBengali-Bold.ttf
  #       - asset: fonts/NotoSerifBengali-Medium.ttf
  #       - asset: fonts/NotoSerifBengali_Condensed-ExtraBold.ttf
